import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — GoalRush Global',
  description: 'GoalRush Global terms of service — the rules governing your use of our platform.',
  alternates: { canonical: '/terms' },
  robots: { index: false },
};

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using GoalRush Global ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to all terms, do not use the Service.',
  },
  {
    title: '2. Use of the Service',
    body: 'You may use the Service for personal, non-commercial purposes. You must not: scrape or systematically download content, reproduce or redistribute content without permission, use the Service for any unlawful purpose, or attempt to interfere with the security or performance of the platform.',
  },
  {
    title: '3. Intellectual Property',
    body: `All content on GoalRush Global — including AI-generated articles, match reports, and analysis — is the property of GoalRush Global or its licensors. You may share individual articles with attribution but may not republish, repost, or resell content without written permission.`,
  },
  {
    title: '4. AI-Generated Content',
    body: `Some content on GoalRush Global is generated by artificial intelligence (Claude by Anthropic). While we strive for accuracy, AI-generated content may contain errors. Do not rely on it for medical, legal, financial, or betting decisions. Always verify critical information with authoritative sources.`,
  },
  {
    title: '5. Predictions and Gambling',
    body: `Match predictions are provided for entertainment purposes only. GoalRush Global does not endorse gambling. If you choose to bet based on predictions, you do so entirely at your own risk. Please gamble responsibly. If gambling is causing harm, seek help at begambleaware.org.`,
  },
  {
    title: '6. Third-Party Links',
    body: `The Service may contain links to third-party websites. We are not responsible for the content or privacy practices of those sites. Links do not constitute endorsement.`,
  },
  {
    title: '7. Disclaimer of Warranties',
    body: 'The Service is provided "as is" without warranty of any kind. We do not guarantee that the Service will be uninterrupted, error-free, or that live score data will be accurate or up to date at all times.',
  },
  {
    title: '8. Changes to Terms',
    body: `We reserve the right to modify these terms at any time. Material changes will be announced on the site. Continued use after changes constitutes acceptance.`,
  },
];

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 lg:px-6 py-16">
      <h1 className="text-4xl font-display tracking-wider text-white mb-3">TERMS OF SERVICE</h1>
      <p className="text-brand-gray mb-2">Last updated: 1 July 2026</p>
      <p className="text-brand-gray text-sm mb-12">
        Please read these terms carefully before using GoalRush Global.
      </p>
      <div className="space-y-8">
        {SECTIONS.map(s => (
          <div key={s.title} className="gr-card p-6">
            <h2 className="text-white font-semibold mb-3">{s.title}</h2>
            <p className="text-brand-gray text-sm leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>
      <div className="mt-10 flex gap-4">
        <Link href="/privacy" className="text-brand-red text-sm hover:underline">Privacy Policy</Link>
        <Link href="/contact" className="text-brand-red text-sm hover:underline">Contact Us</Link>
      </div>
    </div>
  );
}
