import type { Metadata } from 'next';
import Link from 'next/link';
import { Zap, Globe, Shield, TrendingUp } from 'lucide-react';

export const metadata: Metadata = {
  title: 'About GoalRush Global',
  description: 'GoalRush Global is the AI-powered football media platform delivering live scores, breaking news, and analysis 24/7.',
  alternates: { canonical: '/about' },
};

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 lg:px-6 py-16">
      {/* Logo */}
      <div className="flex items-center gap-3 mb-12">
        <div className="w-14 h-14 bg-red-gradient rounded-2xl flex items-center justify-center">
          <Zap className="w-8 h-8 text-white fill-white"/>
        </div>
        <div>
          <div className="font-display text-3xl tracking-widest text-white">GOALRUSH</div>
          <div className="text-[11px] tracking-[0.4em] text-brand-gold font-semibold">GLOBAL</div>
        </div>
      </div>

      <h1 className="text-4xl font-display tracking-wider text-white mb-6">ABOUT US</h1>
      <p className="text-brand-gray text-lg leading-relaxed mb-12">
        GoalRush Global is an AI-powered football media platform delivering live scores,
        breaking news, transfer updates, and tactical analysis from every major league worldwide — 24/7, never stopping.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
        {[
          { icon: Globe,      title: 'Global Coverage', desc: 'Every major league, cup, and international tournament covered in real time.' },
          { icon: TrendingUp, title: 'AI-Powered',      desc: 'Match reports, predictions, and analysis generated by Claude AI — fast and accurate.' },
          { icon: Shield,     title: 'Always On',       desc: 'Round-the-clock monitoring so you never miss a goal, transfer, or breaking story.' },
        ].map(({ icon: Icon, title, desc }) => (
          <div key={title} className="gr-card p-6">
            <Icon className="w-6 h-6 text-brand-gold mb-3"/>
            <h3 className="text-white font-semibold mb-2">{title}</h3>
            <p className="text-brand-gray text-sm leading-relaxed">{desc}</p>
          </div>
        ))}
      </div>

      <div className="gr-card p-8 mb-8">
        <h2 className="text-white font-semibold text-xl mb-4">Our Mission</h2>
        <p className="text-brand-gray leading-relaxed">
          Football never sleeps — and neither do we. GoalRush Global was built to bring fans closer to the game
          they love with fast, accurate, and intelligent coverage. From World Cup quarter-finals to League One
          Tuesday night fixtures, every match matters.
        </p>
      </div>

      <div className="flex items-center gap-4">
        <Link href="/contact" className="gr-btn-primary px-6">Contact Us</Link>
        <Link href="/" className="gr-btn-ghost px-6">Back to Home</Link>
      </div>
    </div>
  );
}
